---

  - name: copy .my.cnf file with root password credentials
    template: src=templates/root/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

  - name: install xtrabackup
    yum:
      name: https://www.percona.com/downloads/XtraBackup/Percona-XtraBackup-2.4.7/binary/redhat/7/x86_64/percona-xtrabackup-24-2.4.7-1.el7.x86_64.rpm
      state: present
